jobs:
  on: push
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        java: [ '1.6', '9.0.x', '12.0.2' ]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: java -cp java HelloWorldApp
