name: evenpay-devops
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: docker://driv/docker-maven-java-oracle
      - name: checkout code
        uses: actions/checkout@v1
      - name: build docker images 
        run: mvn install
